UTF-8に変更

diff --git a/bin/jma-receipt-program-upgrade.sh.in b/bin/jma-receipt-program-upgrade.sh.in
--- a/bin/jma-receipt-program-upgrade.sh.in
+++ b/bin/jma-receipt-program-upgrade.sh.in
@@ -1,39 +1,21 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV"; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
-PANDALIB=/usr/lib/panda
-COBLIB=/usr/lib/open-cobol
-
-# echo message (default character-code EUC)
-echomsg() {
-  if [ "${LANG}" = "ja_JP.UTF-8" ] || [ "${LANG}" = "ja_JP.UTF8" ]; then
-    echo `echo $1 | nkf -wE`
-  else
-    echo $1
-  fi
-}
-
-if [ `whoami` != "orca" ]; then
-  echomsg "orca•Ê°º•∂°º§«º¬π‘§∑§∆§Ø§¿§µ§§°£"
+if [ `whoami` != "${ORCAUSER}" ]; then
+  echo "${ORCAUSER}„É¶„Éº„Ç∂„Éº„ÅßÂÆüË°å„Åó„Å¶„Åè„Å†„Åï„ÅÑ„ÄÇ"
   exit 1
 fi
 
-PATH=$SITESCRIPTSDIR/allways:$PATCHSCRIPTSDIR/allways:$SCRIPTSDIR/allways:$PATH
-export PATH
-
-COB_LIBRARY_PATH="${PATCHLIBDIR}":"${ORCALIBDIR}":"${PANDALIB}":"${COBLIB}"
 export COB_LIBRARY_PATH
-
 $DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter "JBS0000001PRGMNT,01"
 
+PATH=$SITESCRIPTSDIR/allways:$PATCHSCRIPTSDIR/allways:$SCRIPTSDIR/allways:$PATH
 program_upgrade_online.sh "update" "01"
 
 exit $?
diff --git a/bin/orcvt_exec.sh.in b/bin/orcvt_exec.sh.in
--- a/bin/orcvt_exec.sh.in
+++ b/bin/orcvt_exec.sh.in
@@ -1,29 +1,26 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV" ; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
-export COB_LIBRARY_PATH="$PATCHLIBDIR":"$ORCALIBDIR":/usr/lib/panda:/usr/lib/open-cobol
 
 if [ $# -ne 2 ]; then
     echo
-    echo "•™•◊•∑•Á•Û§¨¿µ§∑§Ø§¢§Í§ﬁ§ª§Û"
+    echo "„Ç™„Éó„Ç∑„Éß„É≥„ÅåÊ≠£„Åó„Åè„ÅÇ„Çä„Åæ„Åõ„Çì"
     echo
     exit 1
 fi
 
 if [ ! -e "$2" ]; then
     echo
-    echo "$2 •’•°•§•Î§¨¬∏∫ﬂ§∑§ﬁ§ª§Û"
+    echo "$2 „Éï„Ç°„Ç§„É´„ÅåÂ≠òÂú®„Åó„Åæ„Åõ„Çì"
     echo
     exit 1
 fi
 
+export COB_LIBRARY_PATH
 cd $exec_prefix
-
 $DBSTUB -dir "$LDDEFDIR"/directory -bd orcabt $1 -parameter $2
