UTF-8に移行 変数の使用

diff --git a/bin/jma-dbsync.sh.in b/bin/jma-dbsync.sh.in
--- a/bin/jma-dbsync.sh.in
+++ b/bin/jma-dbsync.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV" ; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 $DBSYNC -dir "$LDDEFDIR"/directory $*
diff --git a/bin/jma-receipt-db-check.sh.in b/bin/jma-receipt-db-check.sh.in
--- a/bin/jma-receipt-db-check.sh.in
+++ b/bin/jma-receipt-db-check.sh.in
@@ -1,29 +1,22 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
-umask 022
-
-HOME=/home/orca
 VERSIONFL=${DOCDIR}/version
 DBKANRIFL=/tmp/jma-receipt-db-version
 
 SQLSELECT="SELECT * FROM TBL_DBKANRI WHERE KANRICD='ORCADB00';"
 
-DBHOST=localhost
-
 EXITMODE=code
 
 FLAG=`id -u`
 
-if [ "${LANG}" = "ja_JP.eucJP" ] ; then
+if [ "${LANG}" = "ja_JP.UTF-8" ] || [ "${LANG}" = "ja_JP.utf8" ]; then
     JMSG=1
 else
     JMSG=0
@@ -31,7 +24,7 @@ fi
 
 if [ ${FLAG} -ne 0 ] ; then
     if [ ${JMSG} -eq 1 ] ; then
-        echo "ERROR: root∏¢∏¬§«º¬π‘§∑§∆§Ø§¿§µ§§°£"
+        echo "ERROR: rootÊ®©Èôê„ÅßÂÆüË°å„Åó„Å¶„Åè„Å†„Åï„ÅÑ„ÄÇ"
     else
         echo "ERROR: mest be root permission."
     fi
@@ -51,10 +44,10 @@ VERDATA=`echo $VERLIST | awk '{i=split($0,arr,"("); print arr[i]} ' `
 VERDATA1=`echo $VERDATA | awk '{gsub(/[-)]/,""); print } ' `
 
 #echo "VERDATA1=" $VERDATA1
-
-echo "$SQLSELECT" | su - orca -c "psql -o $DBKANRIFL $DBNAME"  
+su - $ORCAUSER -c "psql $PSQLOPTION -c \"$SQLSELECT\" -o $DBKANRIFL $DBNAME"
 
 DBLIST=`awk '/--------|row/ {skip = ! skip; next};/};/ {exit}; (skip == 1) {gsub(/\t| |;/,""); print} ' $DBKANRIFL`
+
 DBVERSION=`echo $DBLIST | awk '{i=split($0,arr,"|"); print arr[2]} ' `
 DBVERSION1=`echo $DBVERSION | awk '{gsub(/[-)]/,""); print } ' `
 
@@ -69,17 +62,18 @@ else
     echo "database version=" $DBVERSION1
     echo
     if [ ${JMSG} -eq 1 ] ; then
-	echo "•—•√•±°º•∏§»•«°º•ø•Ÿ°º•π§Œ•–°º•∏•Á•Û§¨…‘¿∞πÁ§ÚµØ§≥§∑§∆§§§ﬁ§π°£"
+	echo "„Éë„ÉÉ„Ç±„Éº„Ç∏„Å®„Éá„Éº„Çø„Éô„Éº„Çπ„ÅÆ„Éê„Éº„Ç∏„Éß„É≥„Åå‰∏çÊï¥Âêà„ÇíËµ∑„Åì„Åó„Å¶„ÅÑ„Åæ„Åô„ÄÇ"
     else
 	echo "No Good!"
     fi
     if [ "${EXITMODE}" = "file" ] ; then
 	if ! [ -e "SYSCONFDIR"/database-schema-different ] ; then
+	    umask 022
 	    touch "$SYSCONFDIR"/database-schema-different
 	fi
     else
 	exit 99
     fi
-fi 
+fi
 
 rm -f $DBKANRIFL
diff --git a/bin/jma-receipt-db-setup.sh.in b/bin/jma-receipt-db-setup.sh.in
--- a/bin/jma-receipt-db-setup.sh.in
+++ b/bin/jma-receipt-db-setup.sh.in
@@ -1,36 +1,34 @@
 #!/bin/bash
 #
 # Project code name "ORCA"
-# ����ɸ��쥻�ץȥ��ե�(JMA standard receipt software)
+# 日医標準レセプトソフト(JMA standard receipt software)
 #
 # Copyright(C) 2002 JMA(Japan Medical Association)
 #
 # CREATE: 20060124
 #
 #
-# �ǡ����١�����¤�ѹ�������ư
+# データベース構造変更処理起動
 #
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV" ; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
-FLAG=`id -u`
-
-if [ "${LANG}" = "ja_JP.eucJP" ] ; then
+if [ "${LANG}" = "ja_JP.UTF-8" ] || [ "${LANG}" = "ja_JP.utf8" ]; then
     JMSG=1
 else
     JMSG=0
 fi
 
+FLAG=`id -u`
+
 if [ ${FLAG} -ne 0 ] ; then
     if [ ${JMSG} -eq 1 ] ; then
-	echo "ERROR: root���¤Ǽ¹Ԥ��Ƥ���������"
+	echo "ERROR: root権限で実行してください。"
     else
     	echo "ERROR: must be root permission."
     fi
@@ -49,9 +47,9 @@ fi
 
 #
 echo
-echo "version @VERSION@ �ǡ����١�����¤�ѹ�������Ԥ��ޤ���"
+echo "version @VERSION@ データベース構造変更処理を行います。"
 if [ ${JMSG} -eq 1 ] ; then
-    $ECHO_N "��������Ǥ����� (y/n) "$ECHO_C
+    $ECHO_N "よろしいですか？ (y/n) "$ECHO_C
 else
     $ECHO_N "Are you sure? (y/n) "$ECHO_C
 fi
@@ -59,7 +57,7 @@ read REPLY
 
 if [ "$?" -eq 1 ] ; then
     if [ ${JMSG} -eq 1 ] ; then
-	echo "NOTICE: �桼���ˤ������򥭥�󥻥뤵��ޤ�����"
+	echo "NOTICE: ユーザにより処理をキャンセルされました。"
     else
     	echo "NOTICE: user canceled."
     fi
@@ -67,7 +65,7 @@ if [ "$?" -eq 1 ] ; then
 fi
 if [ "$REPLY" != "y" -a "$REPLY" != "Y" ] ; then
     if [ ${JMSG} -eq 1 ] ; then
-	echo "NOTICE: �桼���ˤ������򥭥�󥻥뤵��ޤ�����"
+	echo "NOTICE: ユーザにより処理をキャンセルされました。"
     else
     	echo "NOTICE: user canceled."
     fi
@@ -75,25 +73,25 @@ if [ "$REPLY" != "y" -a "$REPLY" != "Y" ] ; then
 fi
 
 #
-# �ǡ����١�����¸�߳�ǧ
+# データベースの存在確認
 #
 echo
-if su - postgres -c "psql template1 -l|grep ${DBNAME} >/dev/null"
+if su - postgres -c "psql template1 ${PSQLOPTION} -l|grep ${DBNAME} >/dev/null"
 then
     if [ ${JMSG} -eq 1 ] ; then
-	echo "${DBNAME} �ǡ����١�����¸�ߤ��ޤ���"
+	echo "${DBNAME} データベースは存在します。"
     else
 	echo "${DBNAME} Database exist."
     fi
 else
     if [ ${JMSG} -eq 1 ] ; then
-	echo "${DBNAME} �ǡ����١�����¸�ߤ��ޤ���"
+	echo "${DBNAME} データベースは存在しません。"
     else
 	echo "${DBNAME} Database not exist."
     fi
 fi
 #
-# �ᥤ�����
+# メイン処理
 #
 echo
 
@@ -124,14 +122,14 @@ if [ ${RC} -eq 0 ] ; then
 fi
 
 #
-# ������λ
+# 処理終了
 #
 echo
 if [ ${JMSG} -eq 1 ] ; then
     if [ ${RC} -eq 0 ] ; then
-	echo "�����Ϥ��٤ƽ�λ���ޤ���"
+	echo "処理はすべて終了しました"
     else
-        echo "�����ϰ۾ｪλ���ޤ�����"
+        echo "処理は異常終了しました。"
     fi
 else
     if [ ${RC} -eq 0 ] ; then
