DBLISTは取得し直す必要があったので修正 create_dbpassはスクリプト毎に処理するように変更 成功時のメッセージは減らす

diff --git a/bin/jma-receipt-db-check.sh.in b/bin/jma-receipt-db-check.sh.in
--- a/bin/jma-receipt-db-check.sh.in
+++ b/bin/jma-receipt-db-check.sh.in
@@ -8,7 +8,6 @@ fi
 . $JMARECEIPT_ENV
 
 VERSIONFL=${DOCDIR}/version
-DBKANRIFL=/tmp/jma-receipt-db-version
 
 SQLSELECT="SELECT * FROM TBL_DBKANRI WHERE KANRICD='ORCADB00';"
 
@@ -37,7 +36,6 @@ else
     EXITMODE=file
 fi
 
-rm -f $DBKANRIFL
 
 VERLIST=`awk '/version/{gsub(/\t| |;/,""); print} ' $VERSIONFL`
 VERDATA=`echo $VERLIST | awk '{i=split($0,arr,"("); print arr[i]} ' `
@@ -46,10 +44,13 @@ VERDATA1=`echo $VERDATA | awk '{gsub(/[-)]/,""); print } ' `
 #echo "VERDATA1=" $VERDATA1
 
 create_pgpass
-su - $ORCAUSER -c "psql $DBCONNOPTION -c \"$SQLSELECT\" -o $DBKANRIFL $DBNAME"
+DBLIST=`su - $ORCAUSER -c "psql $DBCONNOPTION -At -c \"$SQLSELECT\" $DBNAME"`
+RC=$?
 delete_pgpass
-
-DBLIST=`awk '/--------|row/ {skip = ! skip; next};/};/ {exit}; (skip == 1) {gsub(/\t| |;/,""); print} ' $DBKANRIFL`
+if [ $RC -ne 0 ] || [ -z "$DBLIST" ] ; then
+    echo "ERROR: データベース管理情報が読み取れません。処理を中止します"
+    exit 99
+fi
 
 DBVERSION=`echo $DBLIST | awk '{i=split($0,arr,"|"); print arr[2]} ' `
 DBVERSION1=`echo $DBVERSION | awk '{gsub(/[-)]/,""); print } ' `
@@ -78,4 +79,4 @@ else
     fi
 fi
 
-rm -f $DBKANRIFL
+exit 0
diff --git a/init/orca-db-create.sh.in b/init/orca-db-create.sh.in
--- a/init/orca-db-create.sh.in
+++ b/init/orca-db-create.sh.in
@@ -7,6 +7,15 @@ if [ ! -f ${JMARECEIPT_ENV} ]; then
 fi
 . $JMARECEIPT_ENV
 
+err () {
+  MSG=$1
+  NUM=$2
+  delete_pgpass
+  echo "ERROR: ${MSG}" | tee -a $INSTALLLOG
+  exit ${NUM}
+}
+
+create_pgpass
 if [ -z "$DBENCODING" ]
 then
     DBENCODING="EUC-JP"
@@ -28,8 +37,7 @@ if [ x"$DBHOST" = "x" ]; then
     then
 	su - postgres -c "createuser ${DBCONNOPTION} --createdb --no-superuser --no-createrole ${DBUSER}"
 	if [ $? -ne 0 ] ; then
-	    echo "ERROR: createuser error (${DBUSER})" | tee -a $INSTALLLOG
-	    exit 99
+	    err "createuser error (${DBUSER})" 99
 	fi
     fi
 else
@@ -40,13 +48,11 @@ else
 	if [ -z $USEREXIST ] || [ $RC -ne 0 ] ; then
 	    su - ${ORCAUSER} -c "createuser ${DBCONNOPTION} -U postgres --createdb --no-superuser --no-createrole ${DBUSER}"
 	    if [ $? -ne 0 ] ; then
-		echo "ERROR: createuser error(${DBUSER})" | tee -a $INSTALLLOG
-		exit 99
+		err "createuser error(${DBUSER})" 99
 	    fi
 	    echo "CREATEUSER (${DBUSER})" | tee -a  $INSTALLLOG
 	    if [ $? -ne 0 ] ; then
-		echo "ERROR: set password error" | tee -a $INSTALLLOG
-		exit 99
+		err "set password error"  99
 	    fi
 	    su - ${ORCAUSER} -c "psql ${DBCONNOPTION} -U postgres -c \"${SETPASSWORD}\""
 	fi
@@ -61,14 +67,12 @@ if [ ! -z $DBEXIST ] ; then
     RC=$?
 fi
 if [ $RC -ne 0 ] ; then
-    echo "ERROR: database check error (${DBCHECKSQL})" | tee -a $INSTALLLOG
-    exit 99
+    err "database check error (${DBCHECKSQL})" 99
 fi
 if [ -z $DBEXIST ] ; then
     su - ${ORCAUSER} -c "createdb ${DBCONNOPTION} -lC -Ttemplate0 -E${DBENCODING} \"${DBNAME}\""
     if [ $? -ne 0 ] ; then
-	echo "ERROR: createdb error (${DBNAME})" | tee -a $INSTALLLOG
-	exit 99
+	err "createdb error (${DBNAME})" 99
     fi
     echo "CREATEDB (${DBNAME})" | tee -a  $INSTALLLOG
 fi
@@ -77,10 +81,10 @@ if [ $? -ne 0 ] || [ "$DBKANRICHECK" -eq 0 ]; then
     DBKANRI=`su - ${ORCAUSER} -c "psql ${DBCONNOPTION} -q --set \"ON_ERROR_STOP=1\" ${DBNAME} -f ${INITDIR}/orca_dbkanri_orig.dump" 2>&1`
     RC=$?
     if [ $RC -ne 0 ] ; then
-	echo "ERROR: ${INITDIR}/orca_dbkanri_orig.dump が処理出来ませんでした" | tee -a $INSTALLLOG
 	echo $DBKANRI
-	exit 99
+	err "${INITDIR}/orca_dbkanri_orig.dump が処理出来ませんでした" 99
     fi
     echo "${INITDIR}/orca_dbkanri_orig.dump done." | tee -a  $INSTALLLOG
 fi
+delete_pgpass
 exit 0
diff --git a/init/orca-db-install.sh.in b/init/orca-db-install.sh.in
--- a/init/orca-db-install.sh.in
+++ b/init/orca-db-install.sh.in
@@ -7,6 +7,15 @@ if [ ! -f ${JMARECEIPT_ENV} ]; then
 fi
 . $JMARECEIPT_ENV
 
+err () {
+  MSG=$1
+  NUM=$2
+  delete_pgpass
+  echo "ERROR: ${MSG}" | tee -a $INSTALLLOG $THISTIMELOG
+  exit ${NUM}
+}
+
+create_pgpass
 TMPDIR=/var/tmp
 MSTDIR=orca-$(date +%Y%m%d)
 VERSIONFL=${DOCDIR}/version
@@ -36,16 +45,12 @@ orcawget () {
     fi
     RST=`orcadt_verify.rb --dir . --cacert ${CACERTFILE} ${DBUPGRADEPATH}/$1.p7m 2>&1`
     RC=$?
-    echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG
-#接続確認
-    if [ $RC -eq 0 ] ; then
-#ファイルサイズチェック
-        if [ -s $DWNFL ] ; then
-            return 0;
-        else
-            return 1;
-        fi
+#接続確認 && ファイルサイズチェック
+    if [ $RC -eq 0 ] && [ -s $DWNFL ] ; then
+	echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG > /dev/null
+        return 0;
     else
+	echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG
         return 1;
     fi
 }
@@ -89,16 +94,14 @@ VERDATA2=`echo $VERDATA | awk '{gsub(/[)]/,""); print } ' `
 
 DBLIST=`su - $ORCAUSER -c "psql ${DBCONNOPTION} -At -c \"${SQLSELECT}\" $DBNAME"`
 if [ $? -ne 0 ] || [ -z "$DBLIST" ] ; then
-    echo "ERROR: データベース管理情報が読み取れません。処理を中止します" | tee -a $INSTALLLOG $THISTIMELOG
-    exit 99
+    err "データベース管理情報が読み取れません。処理を中止します" 99
 fi
 DBVERSION=`echo $DBLIST | awk '{i=split($0,arr,"|"); print arr[2]} ' `
 DBVERSION1=`echo $DBVERSION | awk '{gsub(/[-)]/,""); print } ' `
 if [ "$DBVERSION1" -gt "$VERDATA1" ] ; then
-    echo "ERROR: ダウングレードの処理となっています。処理を中止します" | tee -a $INSTALLLOG $THISTIMELOG
     echo "Database: ${DBVERSION1}" | tee -a $INSTALLLOG $THISTIMELOG
     echo " Version: ${VERDATA1}"   | tee -a $INSTALLLOG $THISTIMELOG
-    exit 99
+    err "ダウングレードの処理となっています。処理を中止します" 99
 fi
 
 #DB管理情報更新
@@ -120,28 +123,34 @@ cd $TMPDIR/$MSTDIR
 rm -f *
 if  [ $OFFLINE = "offline" ]; then
     if  [ ! -e $OFFLINEPATH/$UPDKANRIFILE ]; then
-        echo "ERROR: DBレコード管理情報がありませんでした" | tee -a $INSTALLLOG $THISTIMELOG
-        exit 99
+        err "DBレコード管理情報がありませんでした" 99
     fi
     cp $OFFLINEPATH/$UPDKANRIFILE ./
-    echo "DBレコード管理情報を複写しました" | tee -a $INSTALLLOG $THISTIMELOG
+    echo "OFFLINE: DBレコード管理情報を複写しました" | tee -a $INSTALLLOG $THISTIMELOG
 else
     #センタからのDB構造体ダウンロード
     if orcawget $UPDKANRIFILE ; then
-        echo "センタからのDBレコード管理情報のダウンロードが終了しました" | tee -a $INSTALLLOG $THISTIMELOG
+        echo "ONLINE: センタからのDBレコード管理情報のダウンロードが終了しました" | tee -a $INSTALLLOG $THISTIMELOG
     else
-        echo "ERROR: センタからのDBレコード管理情報のダウンロードに失敗しました" | tee -a $INSTALLLOG $THISTIMELOG
-        exit 99
+        err "センタからのDBレコード管理情報のダウンロードに失敗しました" 99
     fi
 fi
+
+DBLIST=`su - $ORCAUSER -c "psql ${DBCONNOPTION} -At -c \"${SQLSELECT}\" $DBNAME"`
+if [ $? -ne 0 ] || [ -z "$DBLIST" ] ; then
+    err "データベース管理情報が読み取れません。処理を中止します" 99
+fi
+DBVERSION=`echo $DBLIST | awk '{i=split($0,arr,"|"); print arr[2]} ' `
+DBVERSION1=`echo $DBVERSION | awk '{gsub(/[-)]/,""); print } ' `
 
 #ダウンロードファイル生成
 RST=`ORCXSMST1 $MSTDIR$DBLIST 2>&1`
 RC=$?
-echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG
 if [ $RC -ne 0 ] ; then
-    echo "ERROR: ダウンロードファイル生成に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-    exit 99
+    echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG
+    err "ダウンロードファイル生成に失敗しました" 99
+else
+    echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG > /dev/null
 fi
 #更新用ダウンロードファイル受信
 #ファイルサイズチェック
@@ -150,6 +159,7 @@ if [ -s $UPDFILE ] ; then
 else
     echo "更新用ファイルはありません" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
     rm -r $TMPDIR/$MSTDIR
+    delete_pgpass
     exit 0
 fi
 
@@ -167,16 +177,14 @@ do
                 cp $OFFLINEPATH/${UPD:35:$LEN} ./
                 echo ${UPD:35:$LEN} "複写が終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
             else
-                echo "ERROR: ${UPD:35:$LEN} 複写に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-                exit 99
+                err "${UPD:35:$LEN} 複写に失敗しました" 99
             fi
         fi
     else
         if orcawget ${UPD:35:$LEN} ; then
             echo ${UPD:35:$LEN} "ダウンロードが終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
         else
-            echo "ERROR: ${UPD:35:$LEN} ダウンロードに失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-            exit 99
+            err "${UPD:35:$LEN} ダウンロードに失敗しました" 99
         fi
     fi
 done
@@ -185,10 +193,9 @@ for UPD in $UPDLIST
 do
     echo $UPD 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
     if orcatar $UPD ; then
-        echo $UPD "解凍処理が終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+        echo "$UPD 解凍処理が終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
     else
-        echo $UPD "解凍処理に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-        exit 99
+        err "$UPD 解凍処理に失敗しました" 99
     fi
 done
 #DB構造変更処理
@@ -211,8 +218,7 @@ do
     for LOG in $LOGLIST
     do
         if [ "${LOG:0:6}" = "ERROR:" ] ; then
-            echo "ERROR: $UDP2 更新処理に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-            exit 99
+            err "$UDP2 更新処理に失敗しました" 99
         fi
     done
 
@@ -224,4 +230,5 @@ done
 echo  "全ての処理が完了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
 
 rm -r $TMPDIR/$MSTDIR
-
+delete_pgpass
+exit 0
