中間ファイルの削除 エラーチェックの追加 ログ出力調整

diff --git a/init/orca-db-clear.sh.in b/init/orca-db-clear.sh.in
--- a/init/orca-db-clear.sh.in
+++ b/init/orca-db-clear.sh.in
@@ -19,10 +19,12 @@ status=0
 if [ -f $PATCHDIR/copying ];	then
     echo "更新プログラム管理テーブルクリア処理スキップ" 2>&1 | tee -a $INSTALLLOG
 else
-    echo "更新プログラム管理テーブルクリア処理開始" 2>&1 | tee -a $INSTALLLOG
-    su - $ORCAUSER -c "psql ${DBCONNOPTION} -e ${DBNAME} -c \"${DELETESQL}\"" 2>&1 | tee -a $INSTALLLOG
-    if [ ${PIPESTATUS[0]} -ne 0 ] ; then
-	echo "NG" | tee -a $INSTALLLOG
+    PGKANRIDEL=`su - $ORCAUSER -c "psql ${DBCONNOPTION} -q ${DBNAME} -c \"${DELETESQL}\"" 2>&1`
+    RC=$?
+    if [ $RC -ne 0 ] ; then
+	echo "${DELETESQL}" | tee -a $INSTALLLOG
+	echo "$PGKANRIDEL"  | tee -a $INSTALLLOG
+	echo "ERROR: tbl_pgkanriが削除出来ませんでした" | tee -a $INSTALLLOG
 	exit 2
     fi
 fi
diff --git a/init/orca-db-create.sh.in b/init/orca-db-create.sh.in
--- a/init/orca-db-create.sh.in
+++ b/init/orca-db-create.sh.in
@@ -14,7 +14,7 @@ fi
 USERCHECKSQL="SELECT usename FROM pg_user WHERE usename = '${DBUSER}';"
 DBCHECKSQL="SELECT datname FROM pg_database WHERE datname = '${DBNAME}';"
 SETPASSWORD="ALTER USER ${DBUSER} password '${DBPASS}';"
-
+DBKANRISQL="SELECT count(*) FROM pg_tables WHERE tablename = 'tbl_dbkanri';"
 INSTALLLOG="$LOGDIR"/orca-db-install-@VERSION@.log
 
 if [ ! -e "$INSTALLLOG" ]; then
@@ -28,7 +28,7 @@ if [ x"$DBHOST" = "x" ]; then
     then
 	su - postgres -c "createuser ${DBCONNOPTION} --createdb --no-superuser --no-createrole ${DBUSER}"
 	if [ $? -ne 0 ] ; then
-	    echo "createuser error" | tee -a $INSTALLLOG
+	    echo "ERROR: createuser error (${DBUSER})" | tee -a $INSTALLLOG
 	    exit 99
 	fi
     fi
@@ -40,14 +40,15 @@ else
 	if [ -z $USEREXIST ] || [ $RC -ne 0 ] ; then
 	    su - ${ORCAUSER} -c "createuser ${DBCONNOPTION} -U postgres --createdb --no-superuser --no-createrole ${DBUSER}"
 	    if [ $? -ne 0 ] ; then
-		echo "createuser error" | tee -a $INSTALLLOG
+		echo "ERROR: createuser error(${DBUSER})" | tee -a $INSTALLLOG
+		exit 99
+	    fi
+	    echo "CREATEUSER (${DBUSER})" | tee -a  $INSTALLLOG
+	    if [ $? -ne 0 ] ; then
+		echo "ERROR: set password error" | tee -a $INSTALLLOG
 		exit 99
 	    fi
 	    su - ${ORCAUSER} -c "psql ${DBCONNOPTION} -U postgres -c \"${SETPASSWORD}\""
-	    if [ $? -ne 0 ] ; then
-		echo "set password error" | tee -a $INSTALLLOG
-		exit 99
-	    fi
 	fi
     fi
 fi
@@ -55,28 +56,31 @@ fi
 # DB
 DBEXIST=`su - ${ORCAUSER} -c "psql ${DBCONNOPTION} template1 -t -c \"${DBCHECKSQL}\""`
 RC=$?
-if [  $RC -ne 0 ] ; then
+if [ ! -z $DBEXIST ] ; then
     DBEXIST=`su - ${ORCAUSER} -c "psql ${DBCONNOPTION} ${DBNAME} -t -c \"${DBCHECKSQL}\""`
     RC=$?
 fi
 if [ $RC -ne 0 ] ; then
-    echo "database check error" | tee -a $INSTALLLOG
+    echo "ERROR: database check error (${DBCHECKSQL})" | tee -a $INSTALLLOG
     exit 99
 fi
 if [ -z $DBEXIST ] ; then
     su - ${ORCAUSER} -c "createdb ${DBCONNOPTION} -lC -Ttemplate0 -E${DBENCODING} \"${DBNAME}\""
     if [ $? -ne 0 ] ; then
-	echo "createdb error" | tee -a $INSTALLLOG
+	echo "ERROR: createdb error (${DBNAME})" | tee -a $INSTALLLOG
 	exit 99
     fi
-    su - ${ORCAUSER} -c "psql ${DBCONNOPTION} -e ${DBNAME} -f ${INITDIR}/orca_dbkanri_orig.dump 2>&1 | tee -a $INSTALLLOG"
-    if [ ${PIPESTATUS[0]} -ne 0 ]
-    then
-	echo "NG" | tee -a $INSTALLLOG
-	exit 99
-    fi
-else
-    echo "Database \"${DBNAME}\" exist." 2>&1 | tee -a $INSTALLLOG
+    echo "CREATEDB (${DBNAME})" | tee -a  $INSTALLLOG
 fi
-echo "Done."
+DBKANRICHECK=`su - ${ORCAUSER} -c "psql ${DBCONNOPTION} -At ${DBNAME} -c \"${DBKANRISQL}\""`
+if [ $? -ne 0 ] || [ "$DBKANRICHECK" -eq 0 ]; then
+    DBKANRI=`su - ${ORCAUSER} -c "psql ${DBCONNOPTION} -q --set \"ON_ERROR_STOP=1\" ${DBNAME} -f ${INITDIR}/orca_dbkanri_orig.dump" 2>&1`
+    RC=$?
+    if [ $RC -ne 0 ] ; then
+	echo "ERROR: ${INITDIR}/orca_dbkanri_orig.dump が処理出来ませんでした" | tee -a $INSTALLLOG
+	echo $DBKANRI
+	exit 99
+    fi
+    echo "${INITDIR}/orca_dbkanri_orig.dump done." | tee -a  $INSTALLLOG
+fi
 exit 0
diff --git a/init/orca-db-install.sh.in b/init/orca-db-install.sh.in
--- a/init/orca-db-install.sh.in
+++ b/init/orca-db-install.sh.in
@@ -7,8 +7,6 @@ if [ ! -f ${JMARECEIPT_ENV} ]; then
 fi
 . $JMARECEIPT_ENV
 
-umask 022
-
 TMPDIR=/var/tmp
 MSTDIR=orca-$(date +%Y%m%d)
 VERSIONFL=${DOCDIR}/version
@@ -24,32 +22,31 @@ LEN=100
 
 INSTALLLOG="$LOGDIR"/orca-db-install-@VERSION@.log
 THISTIMELOG="$LOGDIR"/orca-db-install-thistime.log
-#
 
 PATH=$PATCHSCRIPTSDIR/allways:$SCRIPTSDIR/allways:$PATCHLIBDIR:$ORCALIBDIR:$PATH
 
 orcawget () {
     DWNFL=`echo $1 | awk '{i=split($0,arr,"/"); print arr[i]} ' `
-    if [ ${DWNFL:1:10}	= "XXXXXXXXXX"	] ;	then
-	return 0;
+    if [ ${DWNFL:1:10} = "XXXXXXXXXX" ] ; then
+        return 0;
     fi
 #受信ファイル削除
     if [ -e $DWNFL ] ; then
-#	echo "rm start" $DWNFL
-	rm $DWNFL;
+        rm $DWNFL;
     fi
-    orcadt_verify.rb --dir . --cacert ${CACERTFILE} ${DBUPGRADEPATH}/$1.p7m
+    RST=`orcadt_verify.rb --dir . --cacert ${CACERTFILE} ${DBUPGRADEPATH}/$1.p7m 2>&1`
+    RC=$?
+    echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG
 #接続確認
-    if [ $? -eq 0 ] ; then
-#	echo "wget end OK"
+    if [ $RC -eq 0 ] ; then
 #ファイルサイズチェック
-	if [ -s $DWNFL ] ; then
-	    return 0;
-	else
-	    return 1;
-	fi
+        if [ -s $DWNFL ] ; then
+            return 0;
+        else
+            return 1;
+        fi
     else
-	return 1;
+        return 1;
     fi
 }
 
@@ -60,59 +57,53 @@ orcatar () {
 #解凍処理
     echo $1
     if [ $TAR = "targz" ] ; then
-	tar zxf $TARFL
+        tar zxf $TARFL
     else
-	return 0;
+        return 0;
     fi
 #tar確認
     if [ $? -eq 0 ] ; then
-	echo "tar end OK"
+        echo "tar end OK"
     else
-	echo "tar end NG"
-	return 1;
+        echo "tar end NG"
+        return 1;
     fi
 #ファイルサイズチェック
     if [ -s $LOCALFL ] ; then
-	return 0;
+        return 0;
     else
-	return 1;
+        return 1;
     fi
 }
 
 if [ ! -e "$INSTALLLOG" ]; then
     su - $ORCAUSER -c "touch $INSTALLLOG"
 fi
-su - $ORCAUSER -c "rm -f $THISTIMELOG"
+rm -f $THISTIMELOG
+su - $ORCAUSER -c "touch $THISTIMELOG"
 
-#エラーファイル用フォルダ作成
-if ! [ -d $TMPDIR/orca-mstlog ] ; then
-    cd $TMPDIR
-    mkdir orca-mstlog
-    chown "$ORCAUSER":"$ORCAGROUP" orca-mstlog
-fi
 #整合性チェック
-rm -f $TMPDIR/orca-mstlog/SQLSELECT.TXT
-rm -f $TMPDIR/orca-mstlog/master_log
 VERLIST=`awk '/version/{gsub(/\t| |;/,""); print} ' $VERSIONFL`
 VERDATA=`echo $VERLIST | awk '{i=split($0,arr,"("); print arr[i]} ' `
 VERDATA1=`echo $VERDATA | awk '{gsub(/[-)]/,""); print } ' `
 VERDATA2=`echo $VERDATA | awk '{gsub(/[)]/,""); print } ' `
-echo "VERDATA1=" $VERDATA1
-echo "$SQLSELECT" > $TMPDIR/orca-mstlog/SQLSELECT.TXT
-su - $ORCAUSER -c "psql ${DBCONNOPTION} -o $TMPDIR/orca-mstlog/sql.out -f $TMPDIR/orca-mstlog/SQLSELECT.TXT $DBNAME"
-DBLIST=`awk '/--------|row/ {skip = ! skip; next};/};/ {exit}; (skip == 1) {gsub(/\t| |;/,""); print} ' $TMPDIR/orca-mstlog/sql.out`
-DBVERSION=`echo $DBLIST | awk '{i=split($0,arr,"|"); print arr[2]} ' `
-DBVERSION1=`echo $DBVERSION | awk '{gsub(/[-)]/,""); print } ' `
-#	if [ `echo $DBVERSION1 $VERDATA1 | awk '{print($1<$2) ? "true" : "false"} '` = "true" ];	then
-if [ `echo $DBVERSION1 $VERDATA1 | awk '{print($1<=$2) ? "true" : "false"} '` = "true" ] ; then
-    echo "OK"
-else
-    echo "ダウングレードの処理となっています。処理を中止します" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+
+DBLIST=`su - $ORCAUSER -c "psql ${DBCONNOPTION} -At -c \"${SQLSELECT}\" $DBNAME"`
+if [ $? -ne 0 ] || [ -z "$DBLIST" ] ; then
+    echo "ERROR: データベース管理情報が読み取れません。処理を中止します" | tee -a $INSTALLLOG $THISTIMELOG
     exit 99
 fi
-#整合性チェックここまで
+DBVERSION=`echo $DBLIST | awk '{i=split($0,arr,"|"); print arr[2]} ' `
+DBVERSION1=`echo $DBVERSION | awk '{gsub(/[-)]/,""); print } ' `
+if [ "$DBVERSION1" -gt "$VERDATA1" ] ; then
+    echo "ERROR: ダウングレードの処理となっています。処理を中止します" | tee -a $INSTALLLOG $THISTIMELOG
+    echo "Database: ${DBVERSION1}" | tee -a $INSTALLLOG $THISTIMELOG
+    echo " Version: ${VERDATA1}"   | tee -a $INSTALLLOG $THISTIMELOG
+    exit 99
+fi
+
 #DB管理情報更新
-echo "update tbl_dbkanri set version='$VERDATA2' where kanricd='ORCADB00';" | su - $ORCAUSER -c "psql ${DBCONNOPTION} -e $DBNAME 2>&1 | tee -a $INSTALLLOG $THISTIMELOG"
+echo "update tbl_dbkanri set version='$VERDATA2' where kanricd='ORCADB00';" | su - $ORCAUSER -c "psql ${DBCONNOPTION} -q $DBNAME 2>&1 | tee -a $INSTALLLOG $THISTIMELOG"
 
 #オフラインメンテナンスであるかチェック
 OFFLINEPATH=`echo $DBUPGRADEPATH | sed -ne 's#file://##p'`
@@ -122,40 +113,37 @@ else
     OFFLINE="offline"
 fi
 
-echo $MSTDIR
-echo $UPDFILE
 if ! [ -d $TMPDIR/$MSTDIR ] ; then
-    cd $TMPDIR
-    mkdir $MSTDIR
-    chown "$ORCAUSER":"$ORCAGROUP" $MSTDIR
+    mkdir $TMPDIR/$MSTDIR
+    chown "$ORCAUSER":"$ORCAGROUP" $TMPDIR/$MSTDIR
 fi
 cd $TMPDIR/$MSTDIR
 rm -f *
 if  [ $OFFLINE = "offline" ]; then
-    if  [ -e $OFFLINEPATH/$UPDKANRIFILE ]; then
-	cp $OFFLINEPATH/$UPDKANRIFILE ./
-	echo "DBレコード管理情報を複写しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-    else
-	echo "DBレコード管理情報がありませんでした" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	exit 99
+    if  [ ! -e $OFFLINEPATH/$UPDKANRIFILE ]; then
+        echo "ERROR: DBレコード管理情報がありませんでした" | tee -a $INSTALLLOG $THISTIMELOG
+        exit 99
     fi
+    cp $OFFLINEPATH/$UPDKANRIFILE ./
+    echo "DBレコード管理情報を複写しました" | tee -a $INSTALLLOG $THISTIMELOG
 else
-#センタからのDB構造体ダウンロード
-    if	orcawget $UPDKANRIFILE ;	then
-	echo "センタからのDBレコード管理情報のダウンロードが終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+    #センタからのDB構造体ダウンロード
+    if orcawget $UPDKANRIFILE ; then
+        echo "センタからのDBレコード管理情報のダウンロードが終了しました" | tee -a $INSTALLLOG $THISTIMELOG
     else
-	echo "センタからのDBレコード管理情報のダウンロードに失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+        echo "ERROR: センタからのDBレコード管理情報のダウンロードに失敗しました" | tee -a $INSTALLLOG $THISTIMELOG
         exit 99
     fi
 fi
 
 #DB管理情報の取得
-su - $ORCAUSER -c "psql ${DBCONNOPTION} -o $TMPDIR/orca-mstlog/sql.out -f $TMPDIR/orca-mstlog/SQLSELECT.TXT $DBNAME"
-DBLIST=`awk '/--------|row/ {skip = ! skip; next};/};/ {exit}; (skip == 1) {gsub(/\t| |;/,""); print} ' $TMPDIR/orca-mstlog/sql.out`
+DBLIST=`su - $ORCAUSER -c "psql ${DBCONNOPTION} -Ate -c \"${SQLSELECT}\" $DBNAME"`
 #ダウンロードファイル生成
-ORCXSMST1 $MSTDIR$DBLIST
-if [ $? -ne 0 ]	;	then
-    echo "ダウンロードファイル生成に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+RST=`ORCXSMST1 $MSTDIR$DBLIST 2>&1`
+RC=$?
+echo "$RST" | tee -a $INSTALLLOG $THISTIMELOG
+if [ $RC -ne 0 ] ; then
+    echo "ERROR: ダウンロードファイル生成に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
     exit 99
 fi
 #更新用ダウンロードファイル受信
@@ -165,7 +153,7 @@ if [ -s $UPDFILE ] ; then
 else
     echo "更新用ファイルはありません" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
     rm -r $TMPDIR/$MSTDIR
-    exit 
+    exit 0
 fi
 
 UPDLIST=`awk '{gsub(/\t| |;/,""); print} ' $UPDFILE`
@@ -174,36 +162,36 @@ for UPD in $UPDLIST
 do
     echo ${UPD:35:$LEN}
     if  [ $OFFLINE = "offline" ]; then
-	DWNFL=`echo ${UPD:35:$LEN} | awk '{i=split($0,arr,"/"); print arr[i]} ' `
-	if [ ${DWNFL:1:10}	= "XXXXXXXXXX"	] ;	then
-	    echo ${UPD:35:$LEN} "オリジナルダンプスキップしました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	else
-	    if  [ -e $OFFLINEPATH/${UPD:35:$LEN} ]; then
-		cp $OFFLINEPATH/${UPD:35:$LEN} ./
-		echo ${UPD:35:$LEN} "複写が終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	    else
-		echo ${UPD:35:$LEN} "複写に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	        exit 99
-	    fi
-	fi
+        DWNFL=`echo ${UPD:35:$LEN} | awk '{i=split($0,arr,"/"); print arr[i]} ' `
+        if [ ${DWNFL:1:10} = "XXXXXXXXXX" ] ; then
+            echo ${UPD:35:$LEN} "オリジナルダンプスキップしました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+        else
+            if  [ -e $OFFLINEPATH/${UPD:35:$LEN} ]; then
+                cp $OFFLINEPATH/${UPD:35:$LEN} ./
+                echo ${UPD:35:$LEN} "複写が終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+            else
+                echo "ERROR: ${UPD:35:$LEN} 複写に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+                exit 99
+            fi
+        fi
     else
-	if	orcawget ${UPD:35:$LEN} ;	then
-	    echo ${UPD:35:$LEN} "ダウンロードが終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	else
-	    echo ${UPD:35:$LEN} "ダウンロードに失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	    exit 99
-	fi
+        if orcawget ${UPD:35:$LEN} ; then
+            echo ${UPD:35:$LEN} "ダウンロードが終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+        else
+            echo "ERROR: ${UPD:35:$LEN} ダウンロードに失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+            exit 99
+        fi
     fi
 done
 
 for UPD in $UPDLIST
 do
-#	echo $UPD
-    if	orcatar $UPD ;	then
-	echo $UPD "解凍処理が終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+#       echo $UPD
+    if orcatar $UPD ; then
+        echo $UPD "解凍処理が終了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
     else
-	echo $UPD "解凍処理に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	exit 99
+        echo $UPD "解凍処理に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+        exit 99
     fi
 done
 #DB構造変更処理
@@ -213,29 +201,23 @@ for UPD in $UPDLIST
 do
     UPD1=`echo $UPD | awk '{gsub(/.tar.gz/,".dat"); print} ' `
     UPD2=`echo $UPD1 | awk '{i=split($0,arr,"/"); print arr[i]} ' `
-#SQL
-#
-    if	[ -s $TMPDIR/$MSTDIR/$UPD2 ]; then
-	if	[ "${UPD2:0:7}" = "ORCADBC" ]; then
-	    su - $ORCAUSER -c "bash $TMPDIR/$MSTDIR/$UPD2 \"${DBOPTION}\" ${INSTALLLOG} ${THISTIMELOG}"
-	else
-	    su - $ORCAUSER -c "psql ${DBCONNOPTION} -e $DBNAME < $TMPDIR/$MSTDIR/$UPD2 2>&1 | tee -a $INSTALLLOG $THISTIMELOG"
-	fi
+    if [ -s $TMPDIR/$MSTDIR/$UPD2 ]; then
+        if [ "${UPD2:0:7}" = "ORCADBC" ]; then
+	    echo $UPD2 | tee -a ${INSTALLLOG} ${THISTIMELOG}
+            su - $ORCAUSER -c "bash $TMPDIR/$MSTDIR/$UPD2 \"${DBOPTION}\" ${INSTALLLOG} ${THISTIMELOG}"
+        else
+            su - $ORCAUSER -c "psql ${DBCONNOPTION} -e $DBNAME < $TMPDIR/$MSTDIR/$UPD2 2>&1 | tee -a $INSTALLLOG $THISTIMELOG"
+        fi
+	echo "$TMPDIR/$MSTDIR/$UPD2 done." | tee -a $INSTALLLOG $THISTIMELOG
     fi
-#	LOGLIST=`awk '/NOTICE:/ {skip = !skip; next};/};/ {exit}; (skip == 1) {gsub(/\t| |;/,""); print} ' $TMPDIR/$MSTDIR/log`
-##	LOGLIST=`awk '/ERROR:/{gsub(/\t| |;/,""); print} ' $TMPDIR/$MSTDIR/log`
     LOGLIST=`awk '/ERROR:/{gsub(/\t| |;/,""); print} ' $THISTIMELOG`
     for LOG in $LOGLIST
     do
-	if [ "${LOG:0:6}" = "ERROR:" ];	then
-	    echo $UDP2 "更新処理に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-	    exit 99
-	fi
+        if [ "${LOG:0:6}" = "ERROR:" ] ; then
+            echo "ERROR: $UDP2 更新処理に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
+            exit 99
+        fi
     done
-#	if [ $? -ne 0 ]	;	then 
-#	echo $UDP2 "更新処理に失敗しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-#		exit 99
-#	fi
 
 #DB管理情報更新
 
@@ -243,6 +225,6 @@ do
 done
 
 echo  "全ての処理が完了しました" 2>&1 | tee -a $INSTALLLOG $THISTIMELOG
-#注意☆☆☆テストが終了したら元に戻す
+
 rm -r $TMPDIR/$MSTDIR
 
