診療情報システム対応

diff --git a/scripts/tools/run_receipt_mis_rou.sh.in b/scripts/tools/run_receipt_mis_rou.sh.in
--- a/scripts/tools/run_receipt_mis_rou.sh.in
+++ b/scripts/tools/run_receipt_mis_rou.sh.in
@@ -83,7 +83,7 @@ do
     ARG10="${EXTIME}00"
     ARG16=${HOSPNUM}
     ARG01="${ARG08}AAAABBBBCCCCDDDD${ARG09}"
-    ARG04="/tmp/${ARG16}00OR042ERRAAAABBBBCCCCDDDD.dat"
+    ARG04="${ARG16}00OR042ERRAAAABBBBCCCCDDDD.dat"
  
     $DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter "JBS0000001RECEPT1,${ARG16}"
  
@@ -122,40 +122,44 @@ fi
 #    を毎日と確定の処理区分として流用する
 #    0:毎日、1:確定
 #-------------------------------------------#
-if [ ${5} -eq 0 ]; then
-  SYORINO="0101"
+if [ -e ${MCP_TEMPDIR}/${ARG04} ]; then
+  echo "Skipping because ErrorFile exists"
 else
-  SYORINO="0102"
-fi
+  if [ ${5} -eq 0 ]; then
+    SYORINO="0101"
+  else
+    SYORINO="0102"
+  fi
 
-ARG05=${EXYM}
-ARG06=${EXYMD}
-ARG13="$4/"
-ARG18="127.0.0.1"
-ARG20=${HOSPNUM}
-ARG16="/tmp/${ARG20}00OR044ERRAAAABBBBCCCCDDDD.dat"
-STIME=${EXTIME}
+  ARG05=${EXYM}
+  ARG06=${EXYMD}
+  ARG13="$4/"
+  ARG18="127.0.0.1"
+  ARG20=${HOSPNUM}
+  ARG16="${ARG20}00OR044ERRAAAABBBBCCCCDDDD.dat"
+  STIME=${EXTIME}
  
-export MON_BATCH_ID=$(uuidgen)
-export MON_BATCH_NAME="recept41_mis.sh"
-export MON_BATCH_GROUPNAME="${ARG20}"
-export MON_BATCH_EXTRA="0000001SOKATU"
-export MON_DIRECTORY_PATH="${LDDIRECTORY}"
-export MCP_TENANT=1
+  export MON_BATCH_ID=$(uuidgen)
+  export MON_BATCH_NAME="recept41_mis.sh"
+  export MON_BATCH_GROUPNAME="${ARG20}"
+  export MON_BATCH_EXTRA="0000001SOKATU"
+  export MON_DIRECTORY_PATH="${LDDIRECTORY}"
+  export MCP_TENANT=1
  
-$DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter "JBS0000001SOKATU,${ARG20}"
+  $DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter "JBS0000001SOKATU,${ARG20}"
 
-PARAM="${SYORINO} MISRECE1 \"${ARG06}${STIME}\" 0001 \"${ARG05}\" \"${ARG06}\" \
-       recept41_mis.sh 0000 AAAABBBBCCCCDDDD orcacron prt 1 \
-       \"${ARG13}\" 0000001 SOKATU \"${ARG16}\" 4 cron \
-       2 \"${ARG20}\" 2 ${5} 0 0 99999999 0"
+  PARAM="${SYORINO} MISRECE1 \"${ARG06}${STIME}\" 0001 \"${ARG05}\" \"${ARG06}\" \
+         recept41_mis.sh 0000 AAAABBBBCCCCDDDD orcacron prt 1 \
+         \"${ARG13}\" 0000001 SOKATU \"${ARG16}\" 4 cron \
+         2 \"${ARG20}\" 2 ${5} 0 0 99999999 0"
 
-${MONBATCH} "recept41_mis.sh ${PARAM}"
-R4RC=$?
+  ${MONBATCH} "recept41_mis.sh ${PARAM}"
+  R4RC=$?
 
-if [ ${R4RC} -ne 0 ] ; then
-  delete_pgpass
-  exit ${R4RC}
+  if [ ${R4RC} -ne 0 ] ; then
+    delete_pgpass
+    exit ${R4RC}
+  fi
 fi
 
 #-------------------------------------------#
@@ -208,7 +212,7 @@ do
     ARG10="${EXTIME}00"
     ARG16=${HOSPNUM}
     ARG01="${ARG08}AAAABBBBCCCCDDDD${ARG09}"
-    ARG04="/tmp/${ARG16}00OR042ERRAAAABBBBCCCCDDDD.dat"
+    ARG04="${ARG16}00OR042ERRAAAABBBBCCCCDDDD.dat"
  
     $DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter "JBS0000001RECEPT1,${ARG16}"
  
@@ -247,40 +251,44 @@ fi
 #    を毎日と確定の処理区分として流用する
 #    0:毎日、1:確定
 #-------------------------------------------#
-if [ ${5} -eq 0 ]; then
-  SYORINO="0111"
+if [ -e ${MCP_TEMPDIR}/${ARG04} ]; then
+  echo "Skipping because ErrorFile exists"
 else
-  SYORINO="0112"
-fi
+  if [ ${5} -eq 0 ]; then
+    SYORINO="0111"
+  else
+    SYORINO="0112"
+  fi
 
-ARG05=${EXYM}
-ARG06=${EXYMD}
-ARG13="$4/"
-ARG18="127.0.0.1"
-ARG20=${HOSPNUM}
-ARG16="/tmp/${ARG20}00OR044ERRAAAABBBBCCCCDDDD.dat"
-STIME=${EXTIME}
+  ARG05=${EXYM}
+  ARG06=${EXYMD}
+  ARG13="$4/"
+  ARG18="127.0.0.1"
+  ARG20=${HOSPNUM}
+  ARG16="${ARG20}00OR044ERRAAAABBBBCCCCDDDD.dat"
+  STIME=${EXTIME}
  
-export MON_BATCH_ID=$(uuidgen)
-export MON_BATCH_NAME="recept41_mis.sh"
-export MON_BATCH_GROUPNAME="${ARG20}"
-export MON_BATCH_EXTRA="0000001SOKATU"
-export MON_DIRECTORY_PATH="${LDDIRECTORY}"
-export MCP_TENANT=1
+  export MON_BATCH_ID=$(uuidgen)
+  export MON_BATCH_NAME="recept41_mis.sh"
+  export MON_BATCH_GROUPNAME="${ARG20}"
+  export MON_BATCH_EXTRA="0000001SOKATU"
+  export MON_DIRECTORY_PATH="${LDDIRECTORY}"
+  export MCP_TENANT=1
  
-$DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter "JBS0000001SOKATU,${ARG20}"
+  $DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter "JBS0000001SOKATU,${ARG20}"
 
-PARAM="${SYORINO} MISRECE1 \"${ARG06}${STIME}\" 0001 \"${ARG05}\" \"${ARG06}\" \
-       recept41_mis.sh 0000 AAAABBBBCCCCDDDD orcacron prt 1 \
-       \"${ARG13}\" 0000001 SOKATU \"${ARG16}\" 4 cron \
-       1 \"${ARG20}\" 2 ${5} 0 0 99999999 0"
+  PARAM="${SYORINO} MISRECE1 \"${ARG06}${STIME}\" 0001 \"${ARG05}\" \"${ARG06}\" \
+         recept41_mis.sh 0000 AAAABBBBCCCCDDDD orcacron prt 1 \
+         \"${ARG13}\" 0000001 SOKATU \"${ARG16}\" 4 cron \
+         1 \"${ARG20}\" 2 ${5} 0 0 99999999 0"
 
-${MONBATCH} "recept41_mis.sh ${PARAM}"
-R4RC=$?
+  ${MONBATCH} "recept41_mis.sh ${PARAM}"
+  R4RC=$?
 
-if [ ${R4RC} -ne 0 ] ; then
-  delete_pgpass
-  exit ${R4RC}
+  if [ ${R4RC} -ne 0 ] ; then
+    delete_pgpass
+    exit ${R4RC}
+  fi
 fi
 
 delete_pgpass
