クライアント保存処理実装

diff --git a/scripts/monthly/upload_jibai_receipt.sh.in b/scripts/monthly/upload_jibai_receipt.sh.in
--- a/scripts/monthly/upload_jibai_receipt.sh.in
+++ b/scripts/monthly/upload_jibai_receipt.sh.in
@@ -9,7 +9,7 @@ fi
 
 . $JMARECEIPT_ENV
 
-trap "cleanup" EXIT
+# trap "cleanup" EXIT
 
 #-------------------------------------------#
 #    自賠責レセプトＰＤＦクライアント保存
@@ -19,11 +19,40 @@ trap "cleanup" EXIT
 #        $3 データファイル
 #-------------------------------------------#
 
-LOGFILE=/var/log/jma-receipt/$1$(baesname ${0%.sh}).log
-
+LOG_FILE=/var/log/jma-receipt/$1$(basename ${0%.sh}).log
 LOCAL_TEMPDIR=$(mktemp -dp ${MCP_TEMPDIR})
+MONTH_DIR=${LOCAL_TEMPDIR}/$2
+DATA_FILE=${MCP_TEMPDIR}/$3
 
 cleanup () {
 	rm -Rf ${LOCAL_TEMPDIR}
+  rm -Rf ${DATA_FILE}
 }
 
+mkdir -p ${MONTH_DIR}
+
+while read LINE; do
+  name=$(echo ${LINE:0:43}| sed -e 's/[[:space:]]*$//')
+  sn=${LINE:46:2}
+  tmpfile=${LOCAL_TEMPDIR}/${name}.${sn}.tmp
+  redname=${LINE:48:25}
+  redfile=$(find ${SITEFORMDIR} ${PATCHFORMDIR} ${FORMDIR} -maxdepth 1 -type f -name ${redname} | head -n 1)
+
+  printf '%-20000s' "${LINE:78:20000}" > ${tmpfile}
+
+  layeroption=""
+  [[ $(cat ${tmpfile}) =~ MonpeLayerIn(.*)MonpeLayerOut ]]
+  if [ -n "${BASH_REMATCH[0]}" ]; then
+    layeroption=$(echo "${BASH_REMATCH[1]}" | sed -e "s/ *-L */,/g" | sed -e "s/,/-H /")
+    sed -i -e "s/${BASH_REMATCH[0]}/$(printf %-${#BASH_REMATCH[0]}s ' ')/"  ${tmpfile}
+  fi
+
+  red2embed ${redfile} ${tmpfile} -o ${tmpfile}.red
+  monpe ${layeroption} ${tmpfile}.red -e ${tmpfile}.pdf
+done < ${DATA_FILE}
+
+for f in $(ls ${LOCAL_TEMPDIR}/*.tmp.pdf | cut -b 1-$((${#tmpfile} - 7))) ; do
+  pdftk  $f*.tmp.pdf cat output ${MONTH_DIR}/$(basename $f).pdf
+done
+zip -r ${MONTH_DIR}.zip ${MONTH_DIR}/
+monupload -t misc -s  ${MONTH_DIR}.zip
