monbatch_clog対応

diff --git a/scripts/execshell_main.sh.in b/scripts/execshell_main.sh.in
--- a/scripts/execshell_main.sh.in
+++ b/scripts/execshell_main.sh.in
@@ -30,19 +30,54 @@ esac
 
 export PATH
 
+SHELL_NAME=$(basename $2)
+LOG_FILE=${LOGDIR}/${SHELL_NAME%.sh}.log
+LOG_GZ=${LOG_FILE}.gz
+LOG_TEMP=$(mktemp ${LOGDIR}/${SHELL_NAME%.sh}.XXXXXX)
+LOG_LOCK=${LOGDIR}/jma-log.lock
+
+echo $(date +"%Y-%m-%d %H:%M:%S") $(printf "[%s]" "$$" "BGN" "$@") >> ${LOG_TEMP}
+
 LOGSH="log_shell.sh"
 LOGSHDIR=$SCRIPTSDIR/allways
 [ -e ${PATCHSCRIPTSDIR}/allways/${LOGSH} ] && LOGSHDIR=${PATCHSCRIPTSDIR}/allways
 [ -e ${SITESCRIPTSDIR}/allways/${LOGSH} ]  && LOGSHDIR=${SITESCRIPTSDIR}/allways
 
-${LOGSHDIR}/${LOGSH} "$$" "ST" "$@" &
+${LOGSHDIR}/${LOGSH} "$$" "BGN" "$@" &
 
 bash -c "$2 \"$3\" \"$4\" \"$5\" \"$6\" \"$7\" \"$8\" \"$9\" \"${10}\" \"${11}\" \"${12}\" \"${13}\" \"${14}\" \
         \"${15}\" \"${16}\" \"${17}\" \"${18}\" \"${19}\" \"${20}\" \"${21}\" \"${22}\" \"${23}\" \"${24}\" \
         \"${25}\" \"${26}\" \"${27}\" \"${28}\" \"${29}\" \"${30}\" \"${31}\" \"${32}\" \"${33}\" \"${34}\" \
-        \"${35}\" \"${36}\" \"${37}\" \"${38}\" \"${39}\" \"${40}\" \"${41}\" \"${42}\""
+        \"${35}\" \"${36}\" \"${37}\" \"${38}\" \"${39}\" \"${40}\" \"${41}\" \"${42}\"" 2>&1 | tee -a ${LOG_TEMP}
 RET=$?
 
-${LOGSHDIR}/${LOGSH} "$$" "ED" "$@" &
+${LOGSHDIR}/${LOGSH} "$$" "END" "$@" &
+
+echo $(date +"%Y-%m-%d %H:%M:%S") $(printf "[%s]" "$$" "END" "$@")  >>  ${LOG_TEMP}
+
+
+(
+  flock -w 10 -x 200 || {
+    echo "ERROR: $2 lock timeout" 1>&2
+    exit 1;
+  }
+
+  gzip -c ${LOG_TEMP} >> ${LOG_GZ}
+  if [ -f ${LOG_GZ} ];  then
+    if [ $(stat -c "%s" ${LOG_GZ}) -ge 5242880 ] ; then
+  	  mv ${LOG_GZ}  ${LOG_GZ}.0
+   	  for NUM in $(seq 5 -1 1)
+      do
+        LOG_NEW="${LOG_GZ}.${NUM}"
+        NUM=$(expr ${NUM} - 1)
+        LOG_OLD="${LOG_GZ}.${NUM}"
+        echo mv ${LOG_OLD} ${LOG_NEW}
+        mv ${LOG_OLD} ${LOG_NEW} 2>/dev/null
+      done
+    fi
+  fi
+) 200> "${LOG_LOCK}"
+
+rm ${LOG_TEMP}
 
 exit ${RET}
