scripts/claimディレクトリを追加

diff --git a/scripts/execshell.sh.in b/scripts/execshell.sh.in
--- a/scripts/execshell.sh.in
+++ b/scripts/execshell.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 case "$1" in
@@ -18,6 +16,9 @@ case "$1" in
     ;;
   allways)
     PATH=$SITESCRIPTSDIR/allways:$PATCHSCRIPTSDIR/allways:$SCRIPTSDIR/allways:$PATH
+    ;;
+  claim)
+    PATH=$SITESCRIPTSDIR/claim:$PATCHSCRIPTSDIR/claim:$SCRIPTSDIR/claim:$PATH
     ;;
   shell)
     PATH=$PATH
