patch提供対応

diff --git a/scripts/execshell.sh.in b/scripts/execshell.sh.in
--- a/scripts/execshell.sh.in
+++ b/scripts/execshell.sh.in
@@ -1,4 +1,13 @@
 #!/bin/bash
 
-. ${0%.sh}_main.sh "$@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
+fi
+. $JMARECEIPT_ENV
+
+PATH=${PATCHSCRIPTSDIR}:${SCRIPTSDIR}:${PATH}
+
+. $(basename ${0%.sh}_main.sh) "$@"
 
