logディレクトリはパッケージで作成するためjma-receipt.envから削除 環境変数LOGDIRへ変更

diff --git a/scripts/allways/das-check.sh.in b/scripts/allways/das-check.sh.in
--- a/scripts/allways/das-check.sh.in
+++ b/scripts/allways/das-check.sh.in
@@ -1,17 +1,14 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 HOSPNUM=$1
 HOSPID=$2
-LOGDIR=/var/log/jma-receipt
 
 export DAS_CHECK_HOSPID=$HOSPID
 export CLIENT_CONFIG_FILE="$SYSCONFDIR/das-upload.d/das-upload${HOSPNUM}.conf"
diff --git a/scripts/allways/das-profile.sh.in b/scripts/allways/das-profile.sh.in
--- a/scripts/allways/das-profile.sh.in
+++ b/scripts/allways/das-profile.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 HOSPNUM=$1
@@ -23,7 +21,7 @@ FILE_PROFILE=$DASDIR/$HOSPNUM/profile.tar.gz
 export CSV_PROFILE=/tmp/profile.csv
 PROFILE_COMMAND=`dirname $0`/das-profile.rb
 UPLOAD_COMMAND=$SCRIPTSDIR/monthly/das-upload.rb
-LOGFILE=/var/log/jma-receipt/"$HOSPNUM"das-profile.log
+LOGFILE=$LOGDIR/"$HOSPNUM"das-profile.log
 
 DATE=$(date +'%Y%m%d')
 
diff --git a/scripts/allways/master_upgrade.sh.in b/scripts/allways/master_upgrade.sh.in
--- a/scripts/allways/master_upgrade.sh.in
+++ b/scripts/allways/master_upgrade.sh.in
@@ -1,53 +1,47 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV"; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
-fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
 . $JMARECEIPT_ENV
 
 #------------------------------------
-# $1 : °åÎÅµ¡´Ø¼±ÊÌÈÖ¹æ(HOSPNUM)
-# $2 : ¥¹¡¼¥Ñ¡¼¥Ð¥¤¥¶¡¼
-# $3 : °åÎÅµ¡´Ø¼±ÊÌÈÖ¹æ(HOSPID)
-# $4 : É¸½à¥Þ¥¹¥¿¥¨¥é¡¼¥Õ¥¡¥¤¥ëÌ¾
-# $5 : É¸½à¥Þ¥¹¥¿¥¸¥ç¥Ö£É£Ä
-# $6 : É¸½à¥Þ¥¹¥¿¥·¥§¥ë£É£Ä
-# $7 : ¥é¥¤¥»¥ó¥¹¥Þ¥¹¥¿¥¨¥é¡¼¥Õ¥¡¥¤¥ëÌ¾
-# $8 : ¥é¥¤¥»¥ó¥¹¥Þ¥¹¥¿¥¸¥ç¥Ö£É£Ä
-# $9 : ¥é¥¤¥»¥ó¥¹¥Þ¥¹¥¿¥·¥§¥ë£É£Ä
+# $1 : åŒ»ç™‚æ©Ÿé–¢è­˜åˆ¥ç•ªå·(HOSPNUM)
+# $2 : ã‚¹ãƒ¼ãƒ‘ãƒ¼ãƒã‚¤ã‚¶ãƒ¼
+# $3 : åŒ»ç™‚æ©Ÿé–¢è­˜åˆ¥ç•ªå·(HOSPID)
+# $4 : æ¨™æº–ãƒžã‚¹ã‚¿ã‚¨ãƒ©ãƒ¼ãƒ•ã‚¡ã‚¤ãƒ«å
+# $5 : æ¨™æº–ãƒžã‚¹ã‚¿ã‚¸ãƒ§ãƒ–ï¼©ï¼¤
+# $6 : æ¨™æº–ãƒžã‚¹ã‚¿ã‚·ã‚§ãƒ«ï¼©ï¼¤
+# $7 : ãƒ©ã‚¤ã‚»ãƒ³ã‚¹ãƒžã‚¹ã‚¿ã‚¨ãƒ©ãƒ¼ãƒ•ã‚¡ã‚¤ãƒ«å
+# $8 : ãƒ©ã‚¤ã‚»ãƒ³ã‚¹ãƒžã‚¹ã‚¿ã‚¸ãƒ§ãƒ–ï¼©ï¼¤
+# $9 : ãƒ©ã‚¤ã‚»ãƒ³ã‚¹ãƒžã‚¹ã‚¿ã‚·ã‚§ãƒ«ï¼©ï¼¤
 #------------------------------------
 HOSPNUM=$1
-LOGDIR=/var/log/jma-receipt
 TMPLOG=/tmp/${HOSPNUM}master-upgrade-log.$$
 STARTNAME="${HOSPNUM}master-upgrade.log.gz.0"
 
 MNTRET=0
 MLIRET=0
 
-
-#[ -d ${LOGDIR} ]         || mkdir -p ${LOGDIR}
-
-
 if [ -f ${LOGDIR}/${STARTNAME} ];  then
-	if [ $(stat -c "%s" ${LOGDIR}/${STARTNAME}) -ge 1048576 ] ; then
-		for NUM in `seq 3 -1 1`
-		do
-		  NEWNAME="${STARTNAME%.*}.${NUM}"
-		  NUM=`expr ${NUM} - 1`
-		  OLDNAME="${STARTNAME%.*}.${NUM}"
-		  mv ${LOGDIR}/${OLDNAME} ${LOGDIR}/${NEWNAME} 2>/dev/null
-		done
-	fi
+    if [ $(stat -c "%s" ${LOGDIR}/${STARTNAME}) -ge 1048576 ] ; then
+	for NUM in `seq 3 -1 1`
+	do
+	  NEWNAME="${STARTNAME%.*}.${NUM}"
+	  NUM=`expr ${NUM} - 1`
+	  OLDNAME="${STARTNAME%.*}.${NUM}"
+	  mv ${LOGDIR}/${OLDNAME} ${LOGDIR}/${NEWNAME} 2>/dev/null
+	done
+    fi
 fi
 
-#É¸½à¥Þ¥¹¥¿¹¹¿·
+#æ¨™æº–ãƒžã‚¹ã‚¿æ›´æ–°
 master_standard_upgrade.sh $1 $2 $4 $5 $6 2>&1 | tee ${TMPLOG}
 MNTRET=$?
 if [ ${MNTRET} -ne 1 ]; then
-    #¥é¥¤¥»¥ó¥¹¥Þ¥¹¥¿¹¹¿·
+    #ãƒ©ã‚¤ã‚»ãƒ³ã‚¹ãƒžã‚¹ã‚¿æ›´æ–°
     sleep 1
     master_license_upgrade.sh $1 $2 $3 $7 $8 $9 2>&1 | tee -a ${TMPLOG}
     MLIRET=$?
diff --git a/scripts/daily/das-infection.sh.in b/scripts/daily/das-infection.sh.in
--- a/scripts/daily/das-infection.sh.in
+++ b/scripts/daily/das-infection.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 HOSPNUM=$1
@@ -14,8 +12,8 @@ HOSPID=$2
 
 FILE_PREFIX="infection-"
 UPLOAD_COMMAND=$SCRIPTSDIR/monthly/das-upload.rb
-LOG=/var/log/jma-receipt/"$HOSPNUM"datainfection.log
-LOGFILE=/var/log/jma-receipt/"$HOSPNUM"datainfection1.log
+LOG=$LOGDIR/"$HOSPNUM"datainfection.log
+LOGFILE=$LOGDIR/"$HOSPNUM"datainfection1.log
 
 if [ -e $LOGFILE ]; then
   cat $LOGFILE >> $LOG
diff --git a/scripts/daily/das-infection2.sh.in b/scripts/daily/das-infection2.sh.in
--- a/scripts/daily/das-infection2.sh.in
+++ b/scripts/daily/das-infection2.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 HOSPNUM=${1}
@@ -15,8 +13,8 @@ KIDONO=${3}
 
 FILE_PREFIX="infection"
 UPLOAD_COMMAND=das-upload2.rb
-LOG=/var/log/jma-receipt/"$HOSPNUM"datainfection2.log
-LOGFILE=/var/log/jma-receipt/"$HOSPNUM"datainfection2_real.log
+LOG=$LOGDIR/"$HOSPNUM"datainfection2.log
+LOGFILE=$LOGDIR/"$HOSPNUM"datainfection2_real.log
 
 #if [ -e $LOGFILE ]; then
 #  cat $LOGFILE >> $LOG
diff --git a/scripts/monthly/das-upload.sh.in b/scripts/monthly/das-upload.sh.in
--- a/scripts/monthly/das-upload.sh.in
+++ b/scripts/monthly/das-upload.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 HOSPNUM=$1
@@ -20,7 +18,7 @@ export DAS_CHECK_HOSPID=$HOSPID
 
 FILE_PREFIX="collect-"
 UPLOAD_COMMAND=`dirname $0`/das-upload.rb
-LOGFILE=/var/log/jma-receipt/"$HOSPNUM"datacollect1.log
+LOGFILE=$LOGDIR/"$HOSPNUM"datacollect1.log
 
 for file in `ls "$DASDIR"/"$HOSPNUM"/"$FILE_PREFIX"*tar.gz 2>/dev/null`
 do
