データベースを変更可能にする

diff --git a/scripts/allways/orcbsf01.sh.in b/scripts/allways/orcbsf01.sh.in
--- a/scripts/allways/orcbsf01.sh.in
+++ b/scripts/allways/orcbsf01.sh.in
@@ -1,13 +1,12 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
+
 #-------------------------------------------#
 #    バックアップ処理
 #        $1   TABLE-NAME
@@ -17,16 +16,17 @@ fi
 #        $6   KBEN
 #-------------------------------------------#
 ##
+create_pgpass
+if  [ $6 -ne 1 ]; then
+    if  [ -e $4$5 ]; then
+        rm  $4$5
+    fi
+    pg_dump ${DBCONNOPTION} -O -t $1 $DBNAME > $4$5
+else
+    pg_dump ${DBCONNOPTION} -O -t $1 $DBNAME > /tmp/$2.out
+    cat  /tmp/$2.out  /tmp/$3.out  >  $4$5
+    rm   /tmp/$2.out
+fi
 
-        if  [ $6 -ne 1 ]; then
-            if  [ -e $4$5 ]; then
-                rm  $4$5
-            fi
-            pg_dump -O -t $1 $DBNAME > $4$5
-        else
-            pg_dump -O -t $1 $DBNAME > /tmp/$2.out
-            cat  /tmp/$2.out  /tmp/$3.out  >  $4$5
-            rm   /tmp/$2.out
-        fi
-
-        cat  $4$5  >  /tmp/$3.out
+cat  $4$5  >  /tmp/$3.out
+delete_pgpass
diff --git a/scripts/allways/orcbsf02.sh.in b/scripts/allways/orcbsf02.sh.in
--- a/scripts/allways/orcbsf02.sh.in
+++ b/scripts/allways/orcbsf02.sh.in
@@ -1,13 +1,12 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
+
 #-------------------------------------------#
 #    バックアップ処理
 #        $1   TABLE-NAME
@@ -19,12 +18,12 @@ fi
 #-------------------------------------------#
 ##
 
-        if  [ -e $4$5 ]; then
-            rm  $4$5
-        fi
+if  [ -e $4$5 ]; then
+    rm  $4$5
+fi
+create_pgpass
+pg_dump ${DBCONNOPTION} -O $DBNAME > $4$5
+delete_pgpass
+$DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter JBE0000001ORCBSF1,${7}
 
-        pg_dump -O $DBNAME > $4$5
-
-	$DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter JBE0000001ORCBSF1,${7}
-
-        exit
+exit
diff --git a/scripts/allways/program_upgrade_check_log.sh.in b/scripts/allways/program_upgrade_check_log.sh.in
--- a/scripts/allways/program_upgrade_check_log.sh.in
+++ b/scripts/allways/program_upgrade_check_log.sh.in
@@ -1,15 +1,11 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV"; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
-
-umask 022
 
 #------------------------------------
 # $1 : 処理区分
@@ -17,9 +13,7 @@ umask 022
 # $3 : インストールディレクトリ
 #------------------------------------
 
-HOME=/home/orca
 PRGDIR=orca-prgupwork
-LOGDIR=/var/log/jma-receipt
 
 LOG="$LOGDIR"/program_upgrade_check.log
 
@@ -33,7 +27,9 @@ case "${SYORI}" in
       begin;
       delete from tbl_pgkanri where systemversion = 'check';
       commit;"
-      echo "${SQL}" | psql ${DBNAME}
+      create_pgpass
+      echo "${SQL}" | psql ${DBCONNOPTION} ${DBNAME}
+      delete_pgpass
       exit 0
       ;;
 
@@ -77,8 +73,8 @@ ymd=$(date +'%Y%m%d')
 time=$(date +'%H%M%S')
 
 SQL="select max(pgno) from tbl_pgkanri;"
-
-PGNOMAX=`echo ${SQL} | psql -t -A ${DBNAME}`
+create_pgpass
+PGNOMAX=`echo ${SQL} | psql ${DBCONNOPTION} -t -A ${DBNAME}`
 if [ -z ${PGNOMAX} ]; then
   PGNOMAX=000
 fi
@@ -100,6 +96,7 @@ WHERE
 insert into tbl_pgkanri values ('','check','${PGNO}','${ymd}','${PGNAME}','${UPDATEFLG}','','${INSTALLDIR}','${COMMENT}','','','${ymd}','','${time}');
 commit;"
 
-echo "${SQL}" | psql ${DBNAME}
+echo "${SQL}" | psql ${DBCONNOPTION} ${DBNAME}
+delete_pgpass
 
 exit 0
diff --git a/scripts/allways/siori_pull.sh.in b/scripts/allways/siori_pull.sh.in
--- a/scripts/allways/siori_pull.sh.in
+++ b/scripts/allways/siori_pull.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 #-------------------------------------------#
@@ -62,9 +60,9 @@ master_get.sh ${HOSPNUM} ${TERMID} ${JOBID} ${SHELLID} SIORI ${SRYCD}
 if [ $? -ne 0 ] ; then
   exit $?
 fi
- 
-FLIST=`echo "select photo1_filename || ' ' || photo2_filename || ' ' || photo3_filename from tbl_yakujyo_temp where termid='${TERMID}' and srycd='${SRYCD}' and hospnum=${HOSPNUM};" | psql -Atq ${DBNAME}`
-
+create_pgpass
+FLIST=`echo "select photo1_filename || ' ' || photo2_filename || ' ' || photo3_filename from tbl_yakujyo_temp where termid='${TERMID}' and srycd='${SRYCD}' and hospnum=${HOSPNUM};" | psql ${DBCONNOPTION} -Atq ${DBNAME}`
+delete_pgpass
 #echo $FLIST
 
 for file in $FLIST
diff --git a/scripts/tools/run_master_upgrade.sh.in b/scripts/tools/run_master_upgrade.sh.in
--- a/scripts/tools/run_master_upgrade.sh.in
+++ b/scripts/tools/run_master_upgrade.sh.in
@@ -1,25 +1,21 @@
 #!/bin/bash
 
-LOGFILE=/var/log/jma-receipt/${0%.sh}.log
-RUNDATE=$(date  '+%Y%m%d%H%M%S')
-
-if test -z "$JMARECEIPT_ENV"; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="/n/jma-receipt/etc/jma-receipt.env"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
+LOGFILE="$LOGDIR"/${0%.sh}.log
+RUNDATE=$(date  '+%Y%m%d%H%M%S')
+
 export PATH=${SITESCRIPTSDIR}/allways:${PATCHSCRIPTSDIR}/allways:${SCRIPTSDIR}/allways:$PATH
-
+echo ${ORCALIBDIR}
 export COB_LIBRARY_PATH=${PATCHLIBDIR}:${ORCALIBDIR}:/usr/lib/panda
-
-DBUSER="orca"
-
-if [ `whoami` != "${DBUSER}" ]; then
-    echo   "${DBUSER}ユーザーで実行してください。"
+echo ${COB_LIBRARY_PATH}
+if [ `whoami` != "${ORCAUSER}" ]; then
+    echo   "${ORCAUSER}ユーザーで実行してください。"
     exit 101
 fi
 
@@ -30,8 +26,10 @@ if [ $? -ne 0 ]; then
 fi
 
 #HOSPNUM=01
+create_pgpass
 SQL="select hospnum from tbl_sysbase;"
-HNLIST=`psql ${DBUSER} -t -A -q -c "${SQL}"`
+HNLIST=`psql ${DBCONNOPTION} ${DBNAME} -t -A -q -c "${SQL}"`
+delete_pgpass
 
 for hospnum in ${HNLIST} ; do
   HOSPNUM=`printf "%02d" $hospnum`
@@ -51,7 +49,6 @@ for hospnum in ${HNLIST} ; do
   if [	-e ${HOSPIDFL}	];	then 
     rm ${HOSPIDFL}
   fi
-
   ${DBSTUB} -dir ${LDDIRECTORY} -bd orcabt ORCBCHECKREDL -parameter "${MNTERRFL}"
   if [	-e ${MNTERRFL}	];	then 
     cat ${MNTERRFL}
