情報削除によるジョブキャンセル（検証のため）

diff --git a/scripts/allways/print_prv.sh.in b/scripts/allways/print_prv.sh.in
--- a/scripts/allways/print_prv.sh.in
+++ b/scripts/allways/print_prv.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 #if ! test -d /var/tmp/.orca_ps ; then
 #    mkdir /var/tmp/.orca_ps
@@ -28,6 +26,14 @@ fi
 #        ${22} クライアント印刷ダイアログ表示
 #-------------------------------------------#
 #
+termtrap () {
+  echo "term trap in ${0}."
+  $DBSTUB -dir $LDDIRECTORY -bd orcabt ORCBJOB -parameter JBE${13}${14},${18}
+  exit 1
+}
+
+trap 'termtrap' TERM
+
 ERR_FILE_BASE=${12}
 ERR_FILE_FULL=${MCP_TEMPDIR}/${ERR_FILE_BASE}
 
diff --git a/scripts/execshell.sh.in b/scripts/execshell.sh.in
--- a/scripts/execshell.sh.in
+++ b/scripts/execshell.sh.in
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-if test -z "$JMARECEIPT_ENV" ; then
-    JMARECEIPT_ENV="@jma-receipt-env@"
+JMARECEIPT_ENV="@jma-receipt-env@"
+if [ ! -f ${JMARECEIPT_ENV} ]; then
+    echo "${JMARECEIPT_ENV} does not found."
+    exit 1
 fi
-if ! test -f "$JMARECEIPT_ENV"; then
-    exit 0
-fi
-
 . $JMARECEIPT_ENV
 
 case "$1" in
@@ -35,6 +33,16 @@ LOGSHDIR=$SCRIPTSDIR/allways
 [ -e ${SITESCRIPTSDIR}/allways/${LOGSH} ]  && LOGSHDIR=${SITESCRIPTSDIR}/allways
 
 ${LOGSHDIR}/${LOGSH} "$$" "ST" "$@" &
+
+termtrap () {
+  echo "term trap in ${0}."
+  ${LOGSHDIR}/${LOGSH} "$$" "ED" "$@" &
+  exit 1
+}
+
+trap 'termtrap "$@"' TERM
+
+export R_PID=`ps -o ppid --no-headers -p $$`
 
 bash -c "$2 \"$3\" \"$4\" \"$5\" \"$6\" \"$7\" \"$8\" \"$9\" \"${10}\" \"${11}\" \"${12}\" \"${13}\" \"${14}\" \
         \"${15}\" \"${16}\" \"${17}\" \"${18}\" \"${19}\" \"${20}\" \"${21}\" \"${22}\" \"${23}\" \"${24}\" \
